/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#b0c9e8",
        "on-primary-container": "#7991af",
        "on-secondary-fixed-variant": "#264191",
        "primary-fixed": "#d1e4ff",
        "surface-container-high": "#e2e7ff",
        "tertiary": "#041325",
        "surface-container-highest": "#dae2fd",
        "primary-container": "#0f2942",
        "surface-variant": "#dae2fd",
        "tertiary-container": "#1a283b",
        "primary": "#001428",
        "on-primary-fixed": "#011d35",
        "inverse-on-surface": "#eef0ff",
        "on-error": "#ffffff",
        "on-background": "#131b2e",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#dce1ff",
        "on-tertiary-container": "#818fa6",
        "surface-tint": "#49607c",
        "surface-container-low": "#f2f3ff",
        "secondary-fixed-dim": "#b6c4ff",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d2d9f4",
        "inverse-surface": "#283044",
        "background": "#faf8ff",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#314863",
        "secondary-container": "#8fa7fe",
        "surface-bright": "#faf8ff",
        "on-secondary-fixed": "#00164e",
        "on-surface": "#131b2e",
        "on-tertiary-fixed-variant": "#3a485c",
        "on-surface-variant": "#43474d",
        "tertiary-fixed-dim": "#b9c7e0",
        "on-secondary-container": "#1d3989",
        "outline": "#74777e",
        "surface-container": "#eaedff",
        "inverse-primary": "#b0c9e8",
        "error": "#ba1a1a",
        "secondary": "#4059aa",
        "on-tertiary": "#ffffff",
        "surface": "#faf8ff",
        "tertiary-fixed": "#d5e3fd",
        "outline-variant": "#c3c6ce",
        "on-tertiary-fixed": "#0d1c2f",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "4px",
        "space-md": "12px",
        "space-xl": "24px",
        "space-lg": "16px",
        "space-2xs": "2px",
        "space-sm": "8px",
        "space-2xl": "32px",
        "layout-margin-desktop": "16px",
        "col-gutter": "12px",
        "layout-margin-mobile": "12px",
      },
      fontFamily: {
        sans: ["'Hanken Grotesk'", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
        "body-lg": ["'Hanken Grotesk'", "sans-serif"],
        "headline-lg": ["'Hanken Grotesk'", "sans-serif"],
        "code-num-sm": ["'JetBrains Mono'", "monospace"],
        "code-num-lg": ["'JetBrains Mono'", "monospace"],
        "body-sm": ["'Hanken Grotesk'", "sans-serif"],
        "label-caps": ["'Hanken Grotesk'", "sans-serif"],
        "headline-xl-mobile": ["'Hanken Grotesk'", "sans-serif"],
        "body-md": ["'Hanken Grotesk'", "sans-serif"],
        "headline-xl": ["'Hanken Grotesk'", "sans-serif"],
        "headline-md": ["'Hanken Grotesk'", "sans-serif"],
        "code-num-md": ["'JetBrains Mono'", "monospace"],
      },
      fontSize: {
        "body-lg": ["14px", { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-lg": ["20px", { lineHeight: "26px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "code-num-sm": ["11px", { lineHeight: "14px", letterSpacing: "0em", fontWeight: "400" }],
        "code-num-lg": ["16px", { lineHeight: "20px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "400" }],
        "label-caps": ["10px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "700" }],
        "headline-xl-mobile": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-xl": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["16px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "code-num-md": ["12px", { lineHeight: "16px", letterSpacing: "-0.01em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
